### ISSUE TITLE
Last name not changing in Add Patient Menu

### ISSUE THREAD

**Issue by manaschubby** [manaschubby/MediLink-Pro#4]
On Windows machines, the last name field is not editable when we submit the form without lastname and go back to add the last name. It does not arise on macOS.

The following video shows the issue

https://github.com/manaschubby/MediLink-Pro/assets/37976250/1ca259fa-995f-4754-8092-8daed7ce47c5

**Comment by fiskryeziu** [comment]
istead of alert() try to use something like sweetalert2 this will fix your problem in the appPatient.js it's likely that the alert is blocking the user interaction with the inputs.

**Comment by manaschubby** [comment]
Thank you @fiskryeziu. We are looking into the implementation of sweetalert2. Do you also have any idea why the alert is presenting such an anomalous issue in windows computers and not on Linux and Mac? Is there some workaround on the same without using any other library? 

Thank you very much for your inputs.

**Comment by fiskryeziu** [comment]
When you use the alert function in JavaScript, it triggers a native operating system dialog, which is modal and blocks the execution of JavaScript code until it is closed. In the context of Electron applications, this can cause focus-related issues.Also I tried to make it work without libraries with the help of Notification class  
```javascript
  const notification = new Notification({
        title: 'Alert',
        body: 'Please fill in Name and Blood Group fields.',
      });
      notification.show();
```
But it didn't seem to work that's why I checked the sweetalert2.

**Comment by manaschubby** [comment]
Okay. Thank you for your inputs. We shall use the sweetalert2 library. 
If you wish to work on this issue I can assign this issue to you.

I shall add sweetalert2 to our dependency array.

Thank you for contributing!

**Comment by manaschubby** [comment]
The #15 Pull request solves this issue. We replaced the javascript alert() function with a material UI Dialog modal
